# Generated by Django 3.1.7 on 2021-05-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210503_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='abobora', max_length=25),
            preserve_default=False,
        ),
    ]
