# Generated by Django 3.1.7 on 2021-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='starterbid',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
            preserve_default=False,
        ),
    ]
